[build-system]
requires = ["setuptools", "setuptools-rust"]
build-backend = "setuptools.build_meta"

[project]
name = "pyavd-utils"
version = "0.0.1"

[tool.setuptools.packages.find]
include = ["pyavd_utils"]

[[tool.setuptools-rust.ext-modules]]
target = "pyavd_utils._passwords"
path = "rust/passwords/Cargo.toml"
binding = "PyO3"
