[build-system]
requires = ["setuptools", "setuptools-rust"]
build-backend = "setuptools.build_meta"

[project]
name = "pyavd-utils"
version = "0.0.1"

# TODO: this need to go outside of pyproject if we use this
# [bdist_wheel]
# # Builing the wheel for all python versions above 3.10
# py_limited_api=cp310

[dependency-groups]
pytest = [
    "pytest",
]
coverage = [
    "coverage[toml]",
]

[tool.setuptools.packages.find]
include = ["pyavd_utils"]

[[tool.setuptools-rust.ext-modules]]
target = "pyavd_utils._passwords"
path = "rust/passwords/Cargo.toml"
binding = "PyO3"
