#!/usr/bin/env python3
# Copyright (c) 2023-2026 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.

"""
Generate flat requirements file from pyproject.toml.

This script reads python-avd/pyproject.toml and generates a flat requirements.txt
file with all dependencies from pyavd[ansible-collection] fully expanded.

Usage:
    python scripts/generate_requirements.py

Output:
    ansible_collections/arista/avd/requirements.txt
"""

import sys
from pathlib import Path

try:
    import tomllib
except ImportError:
    import tomli as tomllib


def expand_extras(dependencies: list[str], extras_map: dict[str, list[str]], extra_name: str, seen: set[str] | None = None) -> list[str]:
    """
    Recursively expand extras into flat list of dependencies.
    
    Args:
        dependencies: Base dependencies list
        extras_map: Map of extra names to their dependencies
        extra_name: Name of the extra to expand
        seen: Set of already processed extras (to prevent infinite recursion)
    
    Returns:
        Flat list of all dependencies
    """
    if seen is None:
        seen = set()
    
    if extra_name in seen:
        # Prevent infinite recursion
        return []
    
    seen.add(extra_name)
    
    if extra_name not in extras_map:
        return []
    
    result = []
    
    for dep in extras_map[extra_name]:
        # Check if this dependency is a recursive extra (e.g., "pyavd[ansible-collection]")
        if dep.startswith("pyavd[") and dep.endswith("]"):
            # Extract the extra name
            nested_extra = dep[6:-1]  # Remove "pyavd[" and "]"
            # Recursively expand
            result.extend(expand_extras(dependencies, extras_map, nested_extra, seen))
        else:
            result.append(dep)
    
    return result


def get_pyavd_version(pyavd_init_path: Path) -> str:
    """
    Extract version from pyavd/__init__.py.

    Args:
        pyavd_init_path: Path to pyavd/__init__.py

    Returns:
        Version string
    """
    with pyavd_init_path.open("r") as f:
        for line in f:
            if line.startswith("__version__"):
                # Extract version from line like: __version__ = "6.0.0.dev8"
                return line.split("=")[1].strip().strip('"').strip("'")

    return "unknown"


def generate_requirements(pyproject_path: Path, output_path: Path, extra_name: str = "ansible-collection") -> None:
    """
    Generate flat requirements file from pyproject.toml.

    Args:
        pyproject_path: Path to pyproject.toml
        output_path: Path to output requirements.txt
        extra_name: Name of the extra to expand (default: "ansible-collection")
    """
    # Read pyproject.toml
    with pyproject_path.open("rb") as f:
        data = tomllib.load(f)

    project = data.get("project", {})

    # Get version from pyavd/__init__.py
    pyavd_init_path = pyproject_path.parent / "pyavd" / "__init__.py"
    version = get_pyavd_version(pyavd_init_path)
    
    # Get base dependencies
    base_deps = project.get("dependencies", [])
    
    # Get optional dependencies (extras)
    extras_map = project.get("optional-dependencies", {})
    
    # Expand the requested extra
    extra_deps = expand_extras(base_deps, extras_map, extra_name)
    
    # Combine all dependencies
    all_deps = base_deps + extra_deps
    
    # Remove duplicates while preserving order
    seen = set()
    unique_deps = []
    for dep in all_deps:
        # Normalize for comparison (remove version specifiers)
        dep_name = dep.split("[")[0].split(">=")[0].split("==")[0].split("<")[0].split(">")[0].split("!")[0].strip()
        if dep_name not in seen:
            seen.add(dep_name)
            unique_deps.append(dep)
    
    # Generate requirements.txt content
    lines = [
        "# This file is auto-generated by scripts/generate_requirements.py",
        "# DO NOT EDIT MANUALLY - your changes will be overwritten",
        "#",
        "# This file contains all dependencies from pyavd[ansible-collection] fully expanded.",
        "# It is used by the verify_requirements action plugin to validate the Python environment.",
        "#",
        "# To regenerate this file, run: python scripts/generate_requirements.py",
        "",
    ]

    # Add pyavd with version
    lines.append(f"pyavd=={version}")

    # Add all unique dependencies
    for dep in unique_deps:
        lines.append(dep)
    
    # Write to file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w") as f:
        f.write("\n".join(lines))
        f.write("\n")
    
    print(f"✅ Generated {output_path}")
    print(f"📦 Expanded {len(unique_deps)} dependencies from pyavd[{extra_name}]")
    print("\nDependencies:")
    for dep in unique_deps:
        print(f"  - {dep}")


def main() -> None:
    """Main entry point."""
    # Determine paths
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent
    pyproject_path = repo_root / "python-avd" / "pyproject.toml"
    output_path = repo_root / "ansible_collections" / "arista" / "avd" / "requirements.txt"
    
    if not pyproject_path.exists():
        print(f"❌ Error: {pyproject_path} not found", file=sys.stderr)
        sys.exit(1)
    
    generate_requirements(pyproject_path, output_path)


if __name__ == "__main__":
    main()

